#!/bin/bash
# Create a new branch using the current branch name as the base and appending
# to it. Optionally checkout the new branch if the `-b` flag is used.

checkout=$1 ; shift
append=$1
base=$2

current=$( git symbolic-ref --quiet --short HEAD )

if [ "$checkout" != '-b' ]; then
  base="$append"
  append="$checkout"
  checkout=''
fi

if [ -z "$current" ]; then
  echo 'Current branch name could not be determined.'
  exit 1
fi

if [ -z "$append" ]; then
  echo 'You must specify a name to append to the current branch.'
  exit 1
fi

new_branch="${current}-${append}"

if [ "$checkout" = '-b' ]; then
  git checkout -b $new_branch $base
else
  git branch $new_branch $base
  echo $new_branch
fi
