#!/bin/bash -ex

git_ref=${1:-master}
ack_args=${@:2}
pattern='TODO|NOTE|XXX|placehold\.it|TK|tbd|console\.log'

function committed_files {
  git diff ${git_ref}..HEAD --diff-filter=ACMX -G"$pattern" --name-only
}

function uncommitted_files {
  git ls-files -mo --exclude-standard
}

( committed_files ; uncommitted_files ) \
  | sort -u \
  | xargs ag --heading $ack_args "$pattern"
