#!/bin/bash

ctags -f tags --PHP-kinds=cfiv --exclude='.(git|svn)' --recurse --tag-relative=yes --totals=yes          \
--regex-PHP='/(abstract)?\s+class\s+([^ ]+)/\2/c/'                                                       \
--regex-PHP='/(static|abstract|public|protected|private)\s+(final\s+)?function\s+(\&\s+)?([^ (]+)/\4/f/' \
--regex-PHP='/\$([a-zA-Z_][a-zA-Z0-9_]*)/\1/v/'                                                          \
--regex-PHP='/interface\s+([^ ]+)/\1/i/'
