#!/usr/bin/env bash

function parse_remote_url {
  remote_url=$( git config --get remote.origin.url )
  repo=$( basename "$remote_url" .git )

  user=$( dirname "$remote_url" )
  user=$( echo "$user" | awk -F'[:/]' '{ print $NF }' )

  echo "${user}/${repo}"
}

function parse_upstream {
  upstream=$( git rev-parse --abbrev-ref --symbolic-full-name @{upstream} 2>&- )
  echo "${upstream#origin/}"
}

branch=$( parse_upstream )
repo=$( parse_remote_url )
target="$1"
comparison=""

if [ -z "$branch" ]; then
  echo "Could not determine upstream branch."
  exit 1
fi

if [ -z "$target" ]; then
  comparison="$branch"
else
  comparison="${target}...${branch}"
fi


pull_request_url="https://github.com/${repo}/compare/${comparison}?expand=1"

open "$pull_request_url"
